### ISSUE TITLE
Does label.dir work as it should?

### ISSUE THREAD

**Issue by mmoench16** [ndphillips/VisualResume#10]
First up, really quite like the VisualResume package. I noticed that the following string vector didn't do anything in my timeline dataframe `label.dir = c("left", "right", "left", "left", "left")`.

Can you confirm that this is the right format?

I am not sure it matters but I noticed that in the function code the code is in reverse order to the other customisable elements, i.e. elbow, label.x, label.y etc, namely:

```
if("label.dir" %in% names(timeline) == FALSE) {
   change.label.dir <- TRUE
   timeline$label.dir <- NA
 }
```

**Comment by ndphillips** [comment]
Thanks for catching this, indeed there was a bug in the code. I just pushed an update that should fix it. Let me know if it works for you.

**Comment by mmoench16** [comment]
Excellent. Just updated the package and tested everything. Works a charm. Thank you.
