### ISSUE TITLE
Colors setting

### ISSUE THREAD

**Issue by lorisjunod86** [ndphillips/VisualResume#6]
hi,

I was curious to use your package to customize my resume usually made in Indesign. I am a bit new on R, and I can't see how to customize the colors for the box (like changing it depending of the type (education, job, etc). I tried to make a vector of colors, with n colors according to the n item in the timeline dataframe, but adding col = mycolorvector after the timeline dataframe haven't been usefull. So how can I use the col argument ?

Thanking you in anticipation of your kind understanding,

**Comment by ndphillips** [comment]
Can you reprint you exact code?

**Comment by lorisjunod86** [comment]
Yes, the code worked fine, even by defining the colors vector bedore the Visualresume code, that's a bit strange, I feel sorry to have make you lose time. But I am very gratefull of your help !

**Comment by ndphillips** [comment]
Ok so it's working now?

**Comment by lorisjunod86** [comment]
yes, the hardest is probably to adjust the position of the box, but i had found how to add the code, many thanks for your package by the way !,

**Comment by lorisjunod86** [comment]
I would propose a small change in your code, for the definition of "conflicting.l". I may be wrong, but with  < & timeline$side[i] == timeline$side[-i] > you would avoid to plot two points whose box would overlay themselves in the time line, but which arent display on the same side, and therefore aren't really making a conflict.
